name: CI with Pytest in Docker

on:
  pull_request:
    branches: [ "develop", "main" ]

env:
  TEST_IMAGE_NAME: xrpedia-ai-proxy-test
  TEST_MONGODB_URL: ${{ secrets.TEST_MONGODB_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image for Test
      id: build-test-image
      run: docker build --target tester -t ${{ env.TEST_IMAGE_NAME }} .

    - name: Run Test
      id: run-test
      run: |
        docker run --rm \
          -e MONGODB_URL=${{ env.TEST_MONGODB_URL }} \
          ${{ env.TEST_IMAGE_NAME }}
